server:
  port: 9000

spring:
  application:
    name: dsl-dreamlink-identity-backend

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

kafka:
  topic:
    environment: ${KAFKA_TOPIC_ENVIRONMENT}
    application: ${KAFKA_TOPIC_APPLICATION}
    version: ${KAFKA_TOPIC_VERSION}

onelogin:
  base:
    api-url: ${ONELOGIN_API_URL}
  client-id: ${ONELOGIN_CLIENT_ID}
  client-secret: ${ONELOGIN_CLIENT_SECRET}

# Keycloak Configuration
keycloak:
  base:
    api-url: ${KEYCLOAK_API_URL}
  realm: ${KEYCLOAK_REALM}
  client-id: ${KEYCLOAK_CLIENT_ID}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
  idp-alias: onelogin

# Sync Settings
sync:
  fixedDelay: PT1M
  state-file: sync-state.json
  delete-keycloak-users: false

# Logging Configuration
logging:
  level:
    root: INFO