#!/usr/bin/env bash
# Commit-msg hook: validates commit message before commit created

conventional_commit_regex="^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\([a-z \-]+\))?!?: .+$"

commit_message=$(cat "$1")

if [[ "$commit_message" =~ $conventional_commit_regex ]]; then
    echo -e "\e[32mCommit message meets Conventional Commit standards\e[0m"
    exit 0
fi

echo -e "\e[31mThe commit message does not meet Conventional Commit standards\e[0m"
echo "An example of a valid message is: "
echo "  feat(deployment): x tenant updated"
exit 1